# Generated by Django 4.1.7 on 2023-03-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название трека')),
                ('artist', models.CharField(max_length=150, verbose_name='Исполнитель')),
                ('genre', models.CharField(max_length=150, verbose_name='Жанр')),
                ('style', models.CharField(max_length=150, verbose_name='Стиль')),
                ('release', models.DateField(verbose_name='Дата выхода')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст песни')),
            ],
        ),
    ]
