# Generated by Django 4.1.7 on 2023-03-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_songdata_delete_audd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
                ('label', models.CharField(max_length=255)),
                ('catno', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
            ],
        ),
    ]
