# Generated by Django 4.1.7 on 2023-03-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_discogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discogs',
            name='release_id',
        ),
    ]
