# Generated by Django 4.1.7 on 2023-03-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_discogs_release_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discogs',
            name='artist',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
